### ISSUE TITLE
DV parser?

### ISSUE THREAD

**Issue by theweasley** [quietvoid/hdr10plus_parser#25]
Hey man. I'm back again with no so much an issue but an honest query, and wasn't sure how else to ask you. As you'll be aware, DV is now possible on MKVs and I know that DV is similar to HDR10+ in that both are dynamic metadata.

Is it possible to build a parsing script similar to your HDR10+ script that pulls out DV metadata from a source and then is it further possible to inject this metadata into an x265 encode using the x265 encoder to create a DV supported video file?

Figured you might be the right guy to answer this.

**Comment by quietvoid** [comment]
No, it's a proprietary format.

**Comment by theweasley** [comment]
Hey man. Sorry to be reopening this topic. I see you've made a DV parser after all. Thanks so much. Is the process for it similar to how I'd encode for HDR10+ with your script? That is:

1) Get a DV MKV Remux
2) Extract the RPU from it using your script
3) Encode the DV MKV Remux with x265 while giving it the extracted RPU as input

Is that it or would there be more steps involved to get a proper encoded output that supports DV?

Thanks for any help that you can give and thanks so much for the DV tool.

**Comment by quietvoid** [comment]
The support for use with x265 is currently incomplete, it is not advised to use it for anything other than dumping the original RPU.

**Comment by theweasley** [comment]
Ah I see, understood. Thanks. I'll keep an eye out for any updates on this then.

**Comment by cromefire** [comment]
Sorry to bump this _again_, but I've seen there's some new developments. There now seem to be almost all parts of the infrastructure needed in place:
- [Extraction of the rpu](https://github.com/quietvoid/dovi_tool#extract-rpu) 
- (If needed) [RPU Extract to JSON](https://github.com/quietvoid/dovi_tool#export) 
- [The conversion HDR10+ to DV](https://github.com/quietvoid/dovi_tool#from-an-existing-hdr10-metadata-json-file) (which would need to be reversed and I guess this is the point where it's decided if it's possible, if so it seems quite possible that all of this would work)
- [The injection of HDR10+ metadata](https://github.com/quietvoid/hdr10plus_tool#inject) 

This feature could be very useful for some people I guess because:
- There are some TVs (namely Samsung) and many phones (Android) that only have HDR10+ and no DV
- (MKV) DV support is still rather lacking in many cases, my TV for example just doesn't parse DV from it and Kodi also has quite some difficulties and still crashes in many cases with DV support, HDR10+ support on the other hand seems great, both Kodi and the TV accept an MKV with HDR10+ just fine with no problems at all.
- Codec support: if you want to transcode DV stuff into codecs with better compression like AV1 you can't use DV, but you can use HDR10+ just fine

Thank you for all your effort and making all of this stuff even maybe practical, without the the work on dovi_tool and hdr10plus_tool this wouldn't even be nearly possible.

**Comment by quietvoid** [comment]
What are you asking for? Generating HDR10+ from Dolby Vision metadata?
The original issue subject was the RPU injection, which is implemented.

Support for MKV with Kodi works fine for me, but this is probably device dependent.

> Codec support: if you want to transcode DV stuff into codecs with better compression like AV1 you can't use DV, but you can use HDR10+ just fine
This isn't quite true. AV1 supports ST2094-10 metadata.

**Comment by cromefire** [comment]
> What are you asking for? Generating HDR10+ from Dolby Vision metadata?\nThe original issue subject was the RPU injection, which is implemented.\n\nSupport for MKV with Kodi works fine for me, but this is probably device dependent.\n\nCodec support: if you want to transcode DV stuff into codecs with better compression like AV1 you can't use DV, but you can use HDR10+ just fine\nThis isn't quite true. AV1 supports ST2094-10 metadata.

**Comment by cromefire** [comment]
> What are you asking for? Generating HDR10+ from Dolby Vision metadata?
> The original issue subject was the RPU injection, which is implemented.

Yes I suppose it should have it's own issue. I am fully aware it probably not lossless and will not work for every DV profile, but dynamic tone mapping alone can do a great job already, especially while things like 12bit Panels aren't a thing yet. I'll open a seperate issue for it.

> Support for MKV with Kodi works fine for me, but this is probably device dependent.

Most likely, but it seems to be a lot less mature and a lot more device dependent than HDR10+ so that seems like a good alternative.

> > Codec support: if you want to transcode DV stuff into codecs with better compression like AV1 you can't use DV, but you can use HDR10+ just fine
> This isn't quite true. AV1 supports ST2094-10 metadata.

Okay that invalidates the point for AV1, it's still an issue with VP9 but it will eventually be replaced with AV1 in a few years as the "8K" stuff is progressing. But I recognize this might be rather niche.
